title = "Axis"  # From Git
gitRepoUrl = "https://github.com/NeonD00m/axis" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = [["Axis", "Input"]]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "images/logo.png"

# From git:
organizationName = "NeonD00m"
projectName = "Axis"
url = "https://neond00m.github.io"
baseUrl = "/Axis/"
tagline = "An agnostic, simple and versatile input library for ECS"

# [navbar]
# hideableSidebar = true

[navbar]
title = ""

[navbar.logo]
alt = "Axis"
src = "https://raw.githubusercontent.com/NeonD00m/Axis/refs/heads/main/images/logo.png"

# [[navbar.items]]
# href = "https://discord.gg/eJAHVeEPkq"
# label = "Velvera Open Source Discord"
# position = "right"

# [[navbar.items]]
# href = "https://twitter.com/NeonD00m"
# label = "Contact Me on Twitter"
# position = "right"

[footer]
style = "dark"
copyright = "Copyright Â© 2025 NeonD00m. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"

[home]
enabled = true
includeReadme = false # Optional

# [[home.features]]
# title = "Integrated with Jecs"
# description = "One line to replicate either a specific component or a whole entity!"
# image = "images/basics.png"

# [[home.features]]
# title = "Versatile Player-specific replication"
# description = "Allows you to define which players to replicate to in a variety of ways."
# image = "images/players.png"

# [[home.features]]
# title = "Intuitive concepts"
# description = "So intuitive that even a gorilla can get the idea! See this visual explanation:" 
# image = "images/visual-explanation.png"